# 씨네 21

In [17]:
import requests
import time
from bs4 import BeautifulSoup
import pandas as pd

HEADERS = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}

In [18]:
res = requests.get("https://www.cine21.com/movie/rank", headers=HEADERS)
soup = BeautifulSoup(res.text, "html.parser")

items = soup.select("div.list_with_upthumb_item")
print(len(items))

0

In [19]:
res = requests.get("https://cine21.com/movie/rank/list_items/?p=1&idx=1", headers=HEADERS)
data = res.json()
print(data["items"][0])  # 첫 번째 영화 데이터 확인

{'rank': 1, 'hname': '오디세이', 'aud': '2,128,135', 'aud_acc': '2,130,502', 'image': 'https://image.cine21.com/resize/cine21/poster/2026/0713/17_22_12__6a54a03427b8f[X224,320].jpg', 'movie_id': '62585', 'opendate': '2026-08-05', 'point_cine21': '7.55'}

In [20]:
df = pd.DataFrame(data["items"])
df

,rank,hname,aud,aud_acc,image,movie_id,opendate,point_cine21
0,1,오디세이,"2,128,135","2,130,502",https://image.cine21.com/resize/cine21/poster/...,62585,2026-08-05,7.55
1,2,스파이더맨: 브랜드 뉴 데이,"1,950,945","6,085,168",https://image.cine21.com/resize/cine21/poster/...,63091,2026-07-29,7.33
2,3,사랑의 하츄핑: 고래보석의 전설,"425,560","452,974",https://image.cine21.com/resize/cine21/poster/...,63075,2026-08-05,7.00
3,4,호프,"172,427","4,408,041",https://image.cine21.com/resize/cine21/poster/...,62480,2026-07-15,6.83
4,5,미니언즈 & 몬스터즈,"26,735","765,597",https://image.cine21.com/resize/cine21/poster/...,63032,2026-07-15,6.50
5,6,어떻게 해야 했을까?,"21,884","52,030",https://image.cine21.com/resize/cine21/poster/...,63282,2026-07-29,6.50
6,7,다윗,"20,812","290,330",https://image.cine21.com/resize/cine21/poster/...,63108,2026-07-10,5.00
7,8,토이 스토리 5,"12,929","2,940,102",https://image.cine21.com/resize/cine21/poster/...,62799,2026-06-17,6.83
8,9,명탐정 코난: 하이웨이의 타천사,"8,828","8,828","https://image.cine21.com/resize//noimg[X224,32...",NaN,NaN,NaN
9,10,오케이 마담2,"8,420","11,827",https://image.cine21.com/resize/cine21/poster/...,63240,2026-08-12,5.00

In [21]:
all_movie_info = []
all_reviews = []

for idx, row in df_more.iterrows():
    movie_id = row["movie_id"]
    detail_url = f"https://www.cine21.com/movie/info/?movie_id={movie_id}"
    
    res = requests.get(detail_url, headers=HEADERS)
    soup = BeautifulSoup(res.text, "html.parser")
    
    # 1. 기본 정보
    info_items = soup.select("ul.info_list li")
    movie_info = {"movie_id": movie_id, "rank": row["rank"], "title": row["hname"]}
    
    for item in info_items:
        title = item.select_one("p.title")
        if not title:
            continue
        label = title.text.strip()
        if label in ["감독", "출연"]:
            names = [a.text.strip() for a in item.select("a")]
            value = ", ".join(names)
        else:
            value = item.get_text(strip=True).replace(label, "", 1)
        movie_info[label] = value
    
    all_movie_info.append(movie_info)
    
    # 2. 전문가 20자평
    reviews = soup.select("ul.expert_star_list li")
    for r in reviews:
        name = r.select_one("p.name")
        num = r.select_one("p.num")
        review_text = r.select_one("div.review")
        all_reviews.append({
            "movie_id": movie_id,
            "title": row["hname"],
            "reviewer_name": name.text.strip() if name else None,
            "score": num.text.strip() if num else None,
            "review": review_text.text.strip() if review_text else None
        })
    
    print(f"{row['rank']}위 {row['hname']} 완료")
    time.sleep(1)

df_movie_info = pd.DataFrame(all_movie_info)
df_review_all = pd.DataFrame(all_reviews)

1위 오디세이 완료
2위 스파이더맨: 브랜드 뉴 데이 완료
3위 사랑의 하츄핑: 고래보석의 전설 완료
4위 호프 완료
5위 미니언즈 & 몬스터즈 완료
6위 어떻게 해야 했을까? 완료
7위 다윗 완료
8위 토이 스토리 5 완료
9위 명탐정 코난: 하이웨이의 타천사 완료
10위 오케이 마담2 완료
11위 모아나 완료
12위 퍼피 구조대: 더 다이노 무비 완료
13위 투모로우바이투게더 브이알 콘서트 : 엔드리스 라이드 완료
14위 마티 슈프림 완료
15위 경멸 완료
16위 눈동자 완료
17위 시크릿 에이전트 완료
18위 애정만세 완료
19위 지난 여름 완료
20위 파리의 사생활 완료
21위 지느러미 완료
22위 청년 조용기 완료
23위 큐어 완료
24위 왕과 사는 남자 완료
25위 산양들 완료
26위 드림 애니멀즈: 더무비 완료
27위 빈집의 연인들 완료
28위 뱀의 길 완료
29위 피아노 완료
30위 불멸의 존재들. 이집트 박물관의 경이들 완료
31위 하나 코리아 완료
32위 길 위의 뭉치 완료
33위 오피셜히게단디즘 라이브 앳 스타디움 2025 완료
34위 프로젝트 헤일메리 완료
35위 지구 최후의 여자 완료
36위 극장판 엄마 까투리: 도시로 간 까투리 가족 완료
37위 고스트밴드 완료
38위 백치들 완료
39위 남태령 완료
40위 안티 크라이스트 완료
41위 회로 완료
42위 포제션 완료
43위 극장판 도라에몽: 신 진구의 해저비밀성 완료
44위 날씨의 아이 완료
45위 어둠속의 댄서 완료
46위 체리 향기 완료
47위 싱 스트리트 완료
48위 멜랑콜리아 완료
49위 워페어 완료
50위 소영의 노력 완료
51위 신극장판 은혼: 요시와라 대염상 완료
52위 훌라 걸스 완료
53위 정동원 팬콘서트 필름 : 다시 만나는 길 완료
54위 위커 맨 완료
55위 드로스테 저편의 우리들 완료
56위 해피엔드 완료
57위 비긴 어게인 완료
58위 브레이킹 더 웨이브 완료
59위 호컴 완료
60위 콰이강의 다리 완료
61위 희망의 발견, 알래스카에서 완료
62위 군체 완료
63위 오키나와 블루노트 완료
64위 도그빌 완료
65위 태풍 클럽 완료

In [22]:
print("영화 정보:", len(df_movie_info), "개")
print("리뷰 정보:", len(df_review_all), "개")
df_movie_info

영화 정보: 65 개
리뷰 정보: 190 개

,movie_id,rank,title,개봉,등급,시간,관객,장르,국가,감독,출연
0,62585,1,오디세이,2026-08-05,15세이상관람가,172분,"2,130,502명","액션, 모험, 드라마",미국,크리스토퍼 놀란,"맷 데이먼, 톰 홀랜드, 앤 해서웨이"
1,63091,2,스파이더맨: 브랜드 뉴 데이,2026-07-29,12세이상관람가,144분,"6,085,168명","판타지, 어드벤처, 액션",미국,데스틴 크리튼,"톰 홀랜드, 젠데이아 콜먼, 세이디 싱크"
2,63075,3,사랑의 하츄핑: 고래보석의 전설,2026-08-05,전체 관람가,105분,"452,974명",애니메이션,한국,김수훈,"이지현, 조경이"
3,62480,4,호프,2026-07-15,15세이상관람가,156분,"4,408,041명","액션, 스릴러, SF",한국,나홍진,"황정민, 조인성, 정호연"
4,63032,5,미니언즈 & 몬스터즈,2026-07-15,전체 관람가,89분,"765,597명",애니메이션,미국,피에르 코팽,"트레이 파커, 앨리슨 제니"
...,...,...,...,...,...,...,...,...,...,...,...
60,63227,61,"희망의 발견, 알래스카에서",2026-07-04,전체 관람가,98분,"1,617명",다큐멘터리,한국,정형민,NaN
61,62951,62,군체,2026-05-21,15세이상관람가,122분,"5,951,235명","액션, 스릴러",한국,연상호,"전지현, 구교환, 지창욱"
62,NaN,63,오키나와 블루노트,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,5567,64,도그빌,2003-08-012025-10-01 ...,청소년 관람불가,178분,"77,461명","스릴러, 드라마","네덜란드,노르웨이,덴마크",라스 폰 트리에,"니콜 키드먼, 해리엇 안데르손, 로렌 바콜"
64,10062,65,태풍 클럽,2024-06-262025-08-13 ...,15세이상관람가,114분,"22,559명",드라마,일본,소마이 신지,"미카미 유이치, 쿠도 유키, 미우라 토모카즈"

In [23]:
df_review_all

    movie_id  title reviewer_name score                                review
0      62585   오디세이           이자연     8            그리스신화는 놀런을 만나길 오랫동안 기다려왔구나
1      62585   오디세이           송경원     8              늘 해오던 걸 가장 잘 할 수 있는 방식으로
2      62585   오디세이           조현나     7                 죽음과 죄책감을 등에 업은 영웅의 서사
3      62585   오디세이           정재현     7    좋으나 싫으나 미우나 고우나 크리스토퍼 놀런의 여름 블록버스터
4      62585   오디세이           이우빈     6  원전과 어긋나는 놀런의 속도, 이 어긋남을 적절히 조율하려는 음악
..       ...    ...           ...   ...                                   ...
185     5567    도그빌           홍성남     4             영특한 수난극, 덤덤한 실험작, 교활한 교훈극
186    10062  태풍 클럽           이자연     7         다음날이면 모든 게 조용히 사라지겠지만, 그렇다 한들
187    10062  태풍 클럽           박평식     7                     푸른 독을 품고 몸부림치는 날에
188    10062  태풍 클럽           오진우     9       태풍으로 세계의 치부를 발가벗겨버리는 소마이 신지의 역작
189    10062  태풍 클럽           김철홍     9                 오래오래 힘을 잃지 않을 시대의 저기압

[190 rows x 5 columns]

In [25]:
import re

def split_dates(value):
    if pd.isna(value):
        return value, None
    # YYYY-MM-DD 형태 날짜를 모두 찾기
    dates = re.findall(r"\d{4}-\d{2}-\d{2}", str(value))
    if len(dates) >= 2:
        return dates[0], dates[1]  # 최초개봉일, 재개봉일
    elif len(dates) == 1:
        return dates[0], None
    else:
        return value, None

df_movie_info[["개봉일_최초", "재개봉일"]] = df_movie_info["개봉"].apply(
    lambda x: pd.Series(split_dates(x))
)

df_movie_info[df_movie_info["재개봉일"].notna()][["title", "개봉", "개봉일_최초", "재개봉일"]]

,title,개봉,개봉일_최초,재개봉일
17,애정만세,1995-06-172026-08-12 ...,1995-06-17,2026-08-12
28,피아노,2014-12-042026-07-01 ...,2014-12-04,2026-07-01
40,회로,2005-07-242026-07-08 ...,2005-07-24,2026-07-08
43,날씨의 아이,2019-10-302024-10-30 ...,2019-10-30,2024-10-30
44,어둠속의 댄서,2001-02-242019-02-21 ...,2001-02-24,2019-02-21
46,싱 스트리트,2016-05-192026-06-10 ...,2016-05-19,2026-06-10
47,멜랑콜리아,2012-05-172025-01-28 ...,2012-05-17,2025-01-28
51,훌라 걸스,2007-03-012026-07-01 ...,2007-03-01,2026-07-01
55,해피엔드,2025-04-302026-06-24 ...,2025-04-30,2026-06-24
56,비긴 어게인,2024-09-182026-06-17 ...,2024-09-18,2026-06-17
63,도그빌,2003-08-012025-10-01 ...,2003-08-01,2025-10-01
64,태풍 클럽,2024-06-262025-08-13 ...,2024-06-26,2025-08-13

In [26]:
# 1. 기존 지저분한 "개봉" 컬럼 삭제 (이제 필요 없음)
df_movie_info = df_movie_info.drop(columns=["개봉"])

# 2. movie_id 없는 행(오키나와 블루노트 등) 제외
df_movie_info = df_movie_info.dropna(subset=["movie_id"])

# 3. 최종 확인
print(len(df_movie_info), "개 영화")
df_movie_info

59 개 영화

,movie_id,rank,title,등급,시간,관객,장르,국가,감독,출연,개봉일_최초,재개봉일
0,62585,1,오디세이,15세이상관람가,172분,"2,130,502명","액션, 모험, 드라마",미국,크리스토퍼 놀란,"맷 데이먼, 톰 홀랜드, 앤 해서웨이",2026-08-05,NaN
1,63091,2,스파이더맨: 브랜드 뉴 데이,12세이상관람가,144분,"6,085,168명","판타지, 어드벤처, 액션",미국,데스틴 크리튼,"톰 홀랜드, 젠데이아 콜먼, 세이디 싱크",2026-07-29,NaN
2,63075,3,사랑의 하츄핑: 고래보석의 전설,전체 관람가,105분,"452,974명",애니메이션,한국,김수훈,"이지현, 조경이",2026-08-05,NaN
3,62480,4,호프,15세이상관람가,156분,"4,408,041명","액션, 스릴러, SF",한국,나홍진,"황정민, 조인성, 정호연",2026-07-15,NaN
4,63032,5,미니언즈 & 몬스터즈,전체 관람가,89분,"765,597명",애니메이션,미국,피에르 코팽,"트레이 파커, 앨리슨 제니",2026-07-15,NaN
5,63282,6,어떻게 해야 했을까?,12세이상관람가,101분,"52,030명",다큐멘터리,일본,후지노 토모아키,NaN,2026-07-29,NaN
6,63108,7,다윗,전체 관람가,109분,"290,330명",애니메이션,미국,"필 커닝햄, 브렌트 도스","박보검, 장광, 차지연",2026-07-10,NaN
7,62799,8,토이 스토리 5,전체 관람가,101분,"2,940,102명",애니메이션,미국,"앤드류 스탠튼, 맥케나 해리스","톰 행크스, 팀 알렌, 조안 쿠삭",2026-06-17,NaN
9,63240,10,오케이 마담2,15세이상관람가,108분,"11,827명",코미디,한국,이철하,"엄정화, 박성웅, 이상윤",2026-08-12,NaN
10,62818,11,모아나,전체 관람가,115분,"1,021,313명","어드벤처, 액션",미국,토마스 케일,"드웨인 존슨, 캐서린 라가이아, 프랭키 애덤스",2026-07-08,NaN
11,63117,12,퍼피 구조대: 더 다이노 무비,전체 관람가,88분,"3,001명",애니메이션,미국,캘런 브런커,"문남숙, 정선혜, 박지윤",2026-08-13,NaN
13,63001,14,마티 슈프림,15세이상관람가,149분,"131,849명","스포츠, 드라마",미국,조쉬 사프디,"티모시 샬라메, 기네스 팰트로, 오데사 아지온",2026-07-01,NaN
14,2417,15,경멸,15세이상관람가,105분,"9,576명",드라마,"프랑스,이탈리아",장 뤽 고다르,"미셸 피콜리, 브리지트 바르도, 잭 팰런스",NaN,NaN
15,63186,16,눈동자,15세이상관람가,105분,"1,541,466명",스릴러,한국,염지호,"신민아, 김남희, 이승룡",2026-06-24,NaN
16,62309,17,시크릿 에이전트,15세이상관람가,160분,"19,534명","범죄, 드라마",브라질,클레베르 멘돈사 필류,바그너 모라,2026-07-08,NaN
17,926,18,애정만세,15세이상관람가,117분,"19,975명",드라마,대만,차이밍량,"양귀매, 이강생, 진소영",1995-06-17,2026-08-12
19,63225,20,파리의 사생활,15세이상관람가,102분,"8,858명",드라마,영국,레베카 즐로토프스키,"조디 포스터, 비르지니 에피라, 마티유 아말릭",2026-07-15,NaN
20,62907,21,지느러미,15세이상관람가,83분,"8,006명",드라마,한국,박세영,"연예지, 김푸름, 고우",2026-07-22,NaN
21,63296,22,청년 조용기,전체 관람가,99분,862명,다큐멘터리,한국,권혁만,"유열, 양동근",2026-09-11,NaN
22,2573,23,큐어,15세이상관람가,111분,"35,513명","스릴러, 범죄",일본,구로사와 기요시,"야쿠쇼 코지, 하기와라 마사토, 우지키 츠요시",2022-07-06,NaN
23,62893,24,왕과 사는 남자,12세이상관람가,116분,"16,325,796명","시대극, 드라마",한국,장항준,"유해진, 박지훈, 유지태",2026-02-04,NaN
24,62833,25,산양들,12세이상관람가,107분,"5,694명",드라마,한국,유재욱,"박혜진, 이승연, 박효은",2026-07-29,NaN
25,63248,26,드림 애니멀즈: 더무비,전체 관람가,90분,"44,157명",애니메이션,일본,타케키요 히토시,NaN,2026-07-24,NaN
26,62280,27,빈집의 연인들,15세이상관람가,93분,539명,"코미디, 멜로·로맨스, 드라마",한국,김태휘,"정애화, 기주봉",2026-08-12,NaN
27,13600,28,뱀의 길,NaN,85분,"4,259명","액션, 범죄, 미스터리",일본,구로사와 기요시,"아이카와 쇼, 카가와 테루유키",2026-07-22,NaN
28,895,29,피아노,청소년 관람불가,121분,"482,946명","멜로·로맨스, 드라마","호주,뉴질랜드,프랑스",제인 캠피온,"홀리 헌터, 하비 케이틀, 안나 파킨",2014-12-04,2026-07-01
29,63331,30,불멸의 존재들. 이집트 박물관의 경이들,전체 관람가,86분,"1,297명",다큐멘터리,이탈리아,NaN,제레미 아이언스,2026-07-29,NaN
30,62839,31,하나 코리아,NaN,105분,"16,568명",드라마,"한국,덴마크",프레드릭 쇨베르,"김민하, 김주령, 안서현",2026-07-08,NaN
31,62390,32,길 위의 뭉치,전체 관람가,93분,383명,애니메이션,한국,"오성윤, 이춘백","도경수, 박소담, 박철민",2026-08-19,NaN
32,63071,33,오피셜히게단디즘 라이브 앳 스타디움 2025,전체 관람가,121분,"14,004명",다큐멘터리,일본,NaN,"후지하라 사토시, 오자사 다이스케, 나라자키 마코토",2026-04-02,NaN
33,63019,34,프로젝트 헤일메리,12세이상관람가,156분,"2,874,985명",SF,미국,"필 로드, 크리스토퍼 밀러","라이언 고슬링, 산드라 휠러",2026-03-18,NaN
35,59434,36,극장판 엄마 까투리: 도시로 간 까투리 가족,전체 관람가,76분,"175,010명",애니메이션,한국,정길훈,"김서영, 이윤희, 김은아",2022-09-08,NaN
36,63314,37,고스트밴드,전체 관람가,82분,431명,애니메이션,한국,금동호,"김연우, 엄상현, 이용신",2026-08-26,NaN
37,3474,38,백치들,청소년 관람불가,117분,"4,855명","드라마, 코미디","덴마크,프랑스,이탈리아,네덜란드,스웨덴",라스 폰 트리에,"보딜 요르겐센, 젠스 알비누스, 안네 루이즈 하싱",2000-05-20,NaN
38,63113,39,남태령,12세이상관람가,114분,"9,001명",다큐멘터리,한국,김현지,NaN,2026-05,NaN
39,27060,40,안티 크라이스트,청소년 관람불가,104분,"5,368명","스릴러, 드라마","프랑스,폴란드,이탈리아,스웨덴,독일,덴마크",라스 폰 트리에,"윌렘 대포, 샤를로뜨 갱스부르",2011-04-14,NaN
40,6344,41,회로,15세이상관람가,118분,"8,602명","스릴러, 공포",일본,구로사와 기요시,"가토 하루히코, 아소 쿠미코, 야쿠쇼 코지",2005-07-24,2026-07-08
41,6653,42,포제션,청소년 관람불가,124분,"4,751명",드라마,"독일,프랑스",안드레이 줄랍스키,"이자벨 아자니, 샘 닐, 마르기트 카르스텐센",2025-10-08,NaN
42,63194,43,극장판 도라에몽: 신 진구의 해저비밀성,NaN,101분,"74,910명",애니메이션,NaN,야지마 테츠오,"윤아영, 김정아, 조현정",2026-07-01,NaN
43,54608,44,날씨의 아이,15세이상관람가,112분,"852,496명","판타지, 애니메이션, 멜로·로맨스",일본,신카이 마코토,"심규혁, 김유림, 최한",2019-10-30,2024-10-30
44,5204,45,어둠속의 댄서,12세이상관람가,140분,"167,525명","뮤지컬, 드라마","덴마크,독일,네덜란드,이탈리아,미국,영국,프랑스,스웨덴,핀란드,아이슬랜드,노르웨이",라스 폰 트리에,"비요크, 까뜨린느 드뇌브, 데이빗 모스",2001-02-24,2019-02-21
45,344,46,체리 향기,12세이상관람가,95분,"20,326명",드라마,"이란,프랑스",압바스 키아로스타미,"호먀윤 엘샤드, 압둘라흐만 바그헤리, 압신 코르시드 바크티아리",1998-01-01,NaN
46,47766,47,싱 스트리트,15세이상관람가,106분,"603,107명","멜로·로맨스, 드라마","미국,아일랜드,영국",존 카니,"퍼디아 월시-필로, 루시 보인턴, 잭 레이너",2016-05-19,2026-06-10
47,30868,48,멜랑콜리아,15세이상관람가,136분,"32,285명","스릴러, 드라마, SF","덴마크,독일,스웨덴,이탈리아,프랑스",라스 폰 트리에,"커스틴 던스트, 샤를로뜨 갱스부르, 키퍼 서덜랜드",2012-05-17,2025-01-28
48,63297,49,워페어,15세이상관람가,95분,156명,"전쟁, 액션, 드라마",미국,"알렉스 가랜드, 레이 멘도사","조셉 퀸, 찰스 멜튼, 코스모 자비스",2026-08-19,NaN
50,63114,51,신극장판 은혼: 요시와라 대염상,15세이상관람가,124분,"81,991명",애니메이션,일본,안도 나오야,"스키타 토모카즈, 사카구치 다이스케, 쿠기미야 리에",2026-05-20,NaN
51,19051,52,훌라 걸스,12세이상관람가,121분,"59,059명",드라마,일본,이상일,"아오이 유우, 마츠유키 야스코, 토요카와 에츠시",2007-03-01,2026-07-01
52,63214,53,정동원 팬콘서트 필름 : 다시 만나는 길,전체 관람가,93분,"16,761명",공연 실황,한국,나상인,정동원,2026-06-26,NaN
53,16998,54,위커 맨,NaN,102분,142명,"범죄, 미스터리, 공포",영국,로빈 하디,"크리스토퍼 리, 에드워드 우드워드, 다이안 실렌토",NaN,NaN
54,58939,55,드로스테 저편의 우리들,12세이상관람가,70분,142명,"코미디, SF",일본,야마구치 준타,"토사 카즈나리, 아사쿠라 아키, 후지타니 리코",2026-08-19,NaN
55,62143,56,해피엔드,15세이상관람가,113분,"149,929명",드라마,일본,네오 소라,"쿠리하라 하야토, 히다카 유키토, 하야시 유타",2025-04-30,2026-06-24
56,42252,57,비긴 어게인,15세이상관람가,104분,"3,689,760명",멜로·로맨스,미국,존 카니,"키이라 나이틀리, 마크 러팔로, 애덤 리바인",2024-09-18,2026-06-17
57,20,58,브레이킹 더 웨이브,청소년 관람불가,159분,"41,744명","멜로·로맨스, 드라마","프랑스,아이슬랜드,스웨덴,덴마크,노르웨이,네덜란드",라스 폰 트리에,"에밀리 왓슨, 스텔란 스카스가드, 캐트린 카틀리지",1996-12-07,NaN
58,63262,59,호컴,15세이상관람가,107분,"10,016명",호러,미국,다미안 맥카시,"아담 스콧, 피터 쿠넌, 데이빗 윌못",2026-07-22,NaN
59,10161,60,콰이강의 다리,12세이상관람가,161분,"183,530명",NaN,"영국,미국",데이비드 린,"윌리엄 홀덴, 잭 호킨스, 알렉 기네스",NaN,NaN
60,63227,61,"희망의 발견, 알래스카에서",전체 관람가,98분,"1,617명",다큐멘터리,한국,정형민,NaN,2026-07-04,NaN
61,62951,62,군체,15세이상관람가,122분,"5,951,235명","액션, 스릴러",한국,연상호,"전지현, 구교환, 지창욱",2026-05-21,NaN
63,5567,64,도그빌,청소년 관람불가,178분,"77,461명","스릴러, 드라마","네덜란드,노르웨이,덴마크",라스 폰 트리에,"니콜 키드먼, 해리엇 안데르손, 로렌 바콜",2003-08-01,2025-10-01
64,10062,65,태풍 클럽,15세이상관람가,114분,"22,559명",드라마,일본,소마이 신지,"미카미 유이치, 쿠도 유키, 미우라 토모카즈",2024-06-26,2025-08-13

In [27]:
# 원래 df_more(65개)랑 비교해서 어떤 영화가 빠졌는지 확인
missing_titles = set(df_more["hname"]) - set(df_movie_info["title"])
print(missing_titles)

{'투모로우바이투게더 브이알 콘서트 : 엔드리스 라이드', '지난 여름', '지구 최후의 여자', '명탐정 코난: 하이웨이의 타천사', '오키나와 블루노트', '소영의 노력'}

# KOBIS API

In [13]:
KOBIS_URL = "http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json"
API_KEY = "ad0c2a0d95fac6a9768aaa616138620d"

from datetime import datetime, timedelta

all_data = []
today = datetime.today()

for i in range(1, 15):  # 어제부터 14일 전까지
    target_date = (today - timedelta(days=i)).strftime("%Y%m%d")
    params = {"key": API_KEY, "targetDt": target_date}
    res = requests.get(KOBIS_URL, params=params)
    box_list = res.json()["boxOfficeResult"]["dailyBoxOfficeList"]
    for entry in box_list:
        entry["targetDt"] = target_date
        all_data.append(entry)
    time.sleep(0.5)

df_kobis = pd.DataFrame(all_data)
df_kobis

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,targetDt
0,1,1,0,OLD,20250654,오디세이,2026-08-05,2828044570,56.2,-2593082690,-47.8,23326825500,257620,-239934,-48.2,2132433,1647,4991,20260810
1,2,2,0,OLD,20262770,스파이더맨: 브랜드 뉴 데이,2026-07-29,1773545300,35.2,-3008945170,-62.9,63655115540,174615,-289302,-62.4,6091008,1590,5518,20260810
2,3,3,0,OLD,20262381,사랑의 하츄핑: 고래보석의 전설,2026-08-05,174337210,3.5,-997676980,-85.1,4276837970,19410,-104155,-84.3,453216,726,1509,20260810
3,4,4,0,OLD,20233219,호프,2026-07-15,146372870,2.9,-190028150,-56.5,47237513560,14523,-17700,-54.9,4408404,562,949,20260810
4,5,5,3,OLD,20264148,어떻게 해야 했을까?,2026-07-29,22904150,0.5,-17519050,-43.3,523077650,2317,-1661,-41.8,52045,70,132,20260810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,6,6,0,OLD,20262902,다윗,2026-07-10,49701550,2.8,2560700,5.4,2254555580,5472,435,8.6,230860,315,388,20260728
136,7,7,0,OLD,20264665,드림 애니멀즈: 더무비,2026-07-24,28063810,1.6,-5460320,-16.3,280384250,3166,-575,-15.4,31311,323,414,20260728
137,8,8,0,NEW,20262770,스파이더맨: 브랜드 뉴 데이,2026-07-29,17586000,1.0,17586000,100,17586000,1254,1254,100,1254,3,5,20260728
138,9,9,0,OLD,20252402,군체,2026-05-21,9713100,0.6,1411500,17,62709465840,967,155,19.1,5951743,128,149,20260728
139,10,10,2,OLD,20262381,사랑의 하츄핑: 고래보석의 전설,2026-08-05,8649000,0.5,4149000,92.2,48689000,961,461,92.2,4951,5,5,20260728

In [28]:
df_movie_info.to_csv("cine21_movie_info.csv", index=False, encoding="utf-8-sig")
df_review_all.to_csv("cine21_reviews.csv", index=False, encoding="utf-8-sig")
df_kobis.to_csv("kobis_boxoffice.csv", index=False, encoding="utf-8-sig")

print("저장 완료!")

저장 완료!

# EDA

In [29]:
df_movie_info.head()

,movie_id,rank,title,등급,시간,관객,장르,국가,감독,출연,개봉일_최초,재개봉일
0,62585,1,오디세이,15세이상관람가,172분,"2,130,502명","액션, 모험, 드라마",미국,크리스토퍼 놀란,"맷 데이먼, 톰 홀랜드, 앤 해서웨이",2026-08-05,NaN
1,63091,2,스파이더맨: 브랜드 뉴 데이,12세이상관람가,144분,"6,085,168명","판타지, 어드벤처, 액션",미국,데스틴 크리튼,"톰 홀랜드, 젠데이아 콜먼, 세이디 싱크",2026-07-29,NaN
2,63075,3,사랑의 하츄핑: 고래보석의 전설,전체 관람가,105분,"452,974명",애니메이션,한국,김수훈,"이지현, 조경이",2026-08-05,NaN
3,62480,4,호프,15세이상관람가,156분,"4,408,041명","액션, 스릴러, SF",한국,나홍진,"황정민, 조인성, 정호연",2026-07-15,NaN
4,63032,5,미니언즈 & 몬스터즈,전체 관람가,89분,"765,597명",애니메이션,미국,피에르 코팽,"트레이 파커, 앨리슨 제니",2026-07-15,NaN

In [30]:
df_review_all.head()

  movie_id title reviewer_name score                                review
0    62585  오디세이           이자연     8            그리스신화는 놀런을 만나길 오랫동안 기다려왔구나
1    62585  오디세이           송경원     8              늘 해오던 걸 가장 잘 할 수 있는 방식으로
2    62585  오디세이           조현나     7                 죽음과 죄책감을 등에 업은 영웅의 서사
3    62585  오디세이           정재현     7    좋으나 싫으나 미우나 고우나 크리스토퍼 놀런의 여름 블록버스터
4    62585  오디세이           이우빈     6  원전과 어긋나는 놀런의 속도, 이 어긋남을 적절히 조율하려는 음악

In [31]:
df_kobis.head()

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,targetDt
0,1,1,0,OLD,20250654,오디세이,2026-08-05,2828044570,56.2,-2593082690,-47.8,23326825500,257620,-239934,-48.2,2132433,1647,4991,20260810
1,2,2,0,OLD,20262770,스파이더맨: 브랜드 뉴 데이,2026-07-29,1773545300,35.2,-3008945170,-62.9,63655115540,174615,-289302,-62.4,6091008,1590,5518,20260810
2,3,3,0,OLD,20262381,사랑의 하츄핑: 고래보석의 전설,2026-08-05,174337210,3.5,-997676980,-85.1,4276837970,19410,-104155,-84.3,453216,726,1509,20260810
3,4,4,0,OLD,20233219,호프,2026-07-15,146372870,2.9,-190028150,-56.5,47237513560,14523,-17700,-54.9,4408404,562,949,20260810
4,5,5,3,OLD,20264148,어떻게 해야 했을까?,2026-07-29,22904150,0.5,-17519050,-43.3,523077650,2317,-1661,-41.8,52045,70,132,20260810